In [1]:
#ANS1
import numpy as np
arr=np.array([10,20,30,40,50])
#(a)
print("AFTER ADDING 2:",arr+2)
#(b)
print("AFTER MULTIPLYING 3:",arr*3)
#(c)
print("AFTER DIVIDING BY 2:",arr/2)




AFTER ADDING 2: [12 22 32 42 52]
AFTER MULTIPLYING 3: [ 30  60  90 120 150]
AFTER DIVIDING BY 2: [ 5. 10. 15. 20. 25.]


In [2]:
#ANS2
#(a)
arr = np.array([1,2,3,6,4,5])
rev_arr=arr[::-1]
print("REVERSED ARRAY:",rev_arr)

#(b)
def most_freq(arr):
  vals,counts=np.unique(arr,return_counts=True)
  most_freq_val=vals[np.argmax(counts)]
  indices=np.where(arr==most_freq_val)[0]
  return most_freq_val,indices

x=np.array([1,2,3,4,5,1,2,1,1,1])
val_x,idx_x=most_freq(x)
print(f"x -> Most Frequent:{val_x},Indices:{idx_x}")

y=np.array([1,1,1,2,3,4,2,4,3,3])
val_y,idx_y=most_freq(y)
print(f"y -> Most Frequent: {val_y}, Indices: {idx_y}")



REVERSED ARRAY: [5 4 6 3 2 1]
x -> Most Frequent:1,Indices:[0 5 7 8 9]
y -> Most Frequent: 1, Indices: [0 1 2]


In [7]:
#ANS3
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
#(a)
print("Access 1st row, 2nd column:",arr[0,1])
#(b)
print("Access 3rd row, 1nd column:",arr[2,0])




Access 1st row, 2nd column: 20
Access 3rd row, 1nd column: 70


In [8]:
#ANS4
amanjot=np.linspace(10,100,25)
print("DIMENSIONS:",amanjot.ndim)
print("SHAPE:",amanjot.shape)
print("TOTAL ELES:",amanjot.size)
print("DATA TYPE:",amanjot.dtype)
print("BYTES CONSUMED:",amanjot.nbytes)

transposed_reshape = amanjot.reshape(25, 1)
print("Transposed via reshape shape:",transposed_reshape.shape)

transposed_T = amanjot.reshape(1, 25).T
print("Transposed via .T shape:",transposed_T.shape)




DIMENSIONS: 1
SHAPE: (25,)
TOTAL ELES: 25
DATA TYPE: float64
BYTES CONSUMED: 200
Transposed via reshape shape: (25, 1)
Transposed via .T shape: (25, 1)


In [15]:
#ANS5
ucs420_amanjot = np.array(
    [[10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]]
)

print("MEAN:", np.mean(ucs420_amanjot))
print("MEDIAN:", np.median(ucs420_amanjot))
print("MAX:", np.max(ucs420_amanjot))
print("MIN:", np.min(ucs420_amanjot))
print("UNIQUE ELEMENTS:", np.unique(ucs420_amanjot))

reshaped_ucs420_amanjot = ucs420_amanjot.reshape(4, 3)
print("\nRESHAPED ARRAY(4X3):\n", reshaped_ucs420_amanjot)

# Resize to 2 rows and 3 columns
resized_ucs420_amanjot= np.resize(ucs420_amanjot,(2, 3))
print("\nRESIZED ARRAY(2x3):\n", resized_ucs420_amanjot)


MEAN: 43.333333333333336
MEDIAN: 37.5
MAX: 90
MIN: 10
UNIQUE ELEMENTS: [10 15 20 30 35 40 50 60 70 80 90]

RESHAPED ARRAY(4X3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

RESIZED ARRAY(2x3):
 [[10 20 30]
 [40 50 60]]
